### PR TITLE
Remove unnecessary unsafe code

### PR DESCRIPTION
**Pull request by Robbepop**
Found this small nit while studying your new SAT solver.

Btw.: Very clean and readable SAT solver codebase! :)

### CODE REVIEW

**Comment by jix** [comment]
Thanks for letting me know! Somehow I was under the impression that a safe way to do this was still pending stabilization, but I see that hasn't been the case for quite some time already :)

I hope you don't mind, but at the moment I don't want to merge any external contributions, as I haven't yet decided on a license for this project and I don't want commits authored by anyone else until the license and contribution info are part of the repository, to make future auditing straight forward.

**Comment by Robbepop** [comment]
If you plan to merge this I would gladly give all rights for the one-liner change to you. :sweat_smile: 
If that's not sufficient (I am not a legal) I'd be happy to just close this and call it a day. ;)

**Comment by jix** [comment]
I had planned to merge this when I get back to working on starlit, after preparing the repo for external contributions (license, CI, etc.) but as that's taking a lot longer than I had anticipated (hopefully really soon now), I'll merge this now :)

**Comment by Robbepop** [comment]
cool! glad to have contributed to such a cool SAT project!

**Pull request merged**
